name: CI

on:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Compile
        run: npm run compile

      - name: Check code formatting
        run: npm run format

      - name: Run tests
        run: npm test

      - name: Run coverage
        run: npm run test:coverage

      - name: Prepare coverage report
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
